class AppLocalization {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appName': 'CivicPulse',
      'wardSubtitle': 'DTU Ward 42',
      'feedTab': 'Feed',
      'tasksTab': 'Tasks',
      'copilotTab': 'Copilot',
      'analyticsTab': 'Analytics',
      'dashboardTab': 'Executive',
      'karmaPoints': 'Karma Points',
      'streak': '7-Day Streak',
      'trustScore': 'Citizen Trust Reliability',
      'leaderboard': 'Ward 42 Leaderboard',
      'reportHazard': 'Report Civic Hazard',
      'scanQr': 'Scan QR to Back Issue',
      'activeSubmission': 'My Active Submission',
      'nearbyRadar': 'Nearby Hazard Radar',
      'supportIssue': 'Support Issue (+10 KP)',
      'backed': 'Backed (+10 KP Earned)',
      'redeemPass': 'Redeem DTC Metro Pass',
      'suggestFix': 'Suggest Fix',
      'liveCameraEnforced': 'Live Camera Sensor Required (Gallery Upload Blocked)',
      'duplicateMergeToast': 'Duplicate detected within 50m! Merged as Upvote & Boosted SLA (+10 KP).',
      'slaMissAlert': 'Urgent Action Required',
      'mapLibreRoute': 'MapLibre Route',
      'resolveNow': 'Resolve Now',
      'tamperProofProof': 'Tamper-Proof Resolution Proof',
      'geofenceValid': 'Within Geofence Range',
      'captureProof': 'Capture Timestamped Proof',
      'uploadProof': 'Upload Proof & Trigger AI Audit',
      'completedAudit': 'Completed (Audit In-Progress)',
      'officerCopilot': 'Officer Copilot',
      'bedrockClaude': 'Bedrock Claude 3',
      'autoDispatch': 'Auto-Dispatch',
      'approvePwd': 'Approve & Route to PWD Works Dept',
      'hotspotLedger': 'Ward 42 Preventive Hotspot Ledger',
      'askCopilot': 'Ask Bedrock Copilot about Ward 42...',
      'reviewQueue': 'Low-Confidence AI Review Queue',
      'coldZones': 'Cold Zones (No Reports in 14d)',
      'wardComparison': 'Ward SLA & Escalation Comparison',
      'securityFooter': 'AWS Cognito RBAC • ap-south-1 (Mumbai) • EXIF AES-256',
      'loginTitle': 'CivicPulse Portal Access',
      'loginSubtitle': 'AI Citizen Triage, Geofenced Proof Audit & Telemetry Dispatch',
      'maskedPhoneNote': 'Citizen phone numbers masked for data privacy (DPDP Act)',
    },
    'hi': {
      'appName': 'सिविकपल्स',
      'wardSubtitle': 'डीटीयू वार्ड 42',
      'feedTab': 'फ़ीड',
      'tasksTab': 'कार्य सूची',
      'copilotTab': 'सह-पायलट',
      'analyticsTab': 'विश्लेषण',
      'dashboardTab': 'अधिकारी डैशबोर्ड',
      'karmaPoints': 'कर्म अंक (KP)',
      'streak': '7-दिवसीय स्ट्रीक',
      'trustScore': 'नागरिक विश्वसनीयता स्कोर',
      'leaderboard': 'वार्ड 42 लीडरबोर्ड',
      'reportHazard': 'नागरिक समस्या रिपोर्ट करें',
      'scanQr': 'क्यूआर स्कैन कर समर्थन दें',
      'activeSubmission': 'मेरी सक्रिय शिकायत',
      'nearbyRadar': 'आस-पास का खतरा रडार',
      'supportIssue': 'समर्थन दें (+10 KP)',
      'backed': 'समर्थन दिया (+10 KP)',
      'redeemPass': 'डीटीसी / मेट्रो पास प्राप्त करें',
      'suggestFix': 'सुझाव दें',
      'liveCameraEnforced': 'केवल लाइव कैमरा मान्य (गैलरी अपलोड प्रतिबंधित है)',
      'duplicateMergeToast': '50 मीटर के भीतर पहले से दर्ज शिकायत मिली! नया वोट जोड़कर SLA तेज किया गया (+10 KP)।',
      'slaMissAlert': 'तत्काल कार्रवाई आवश्यक',
      'mapLibreRoute': 'मानचित्र दिशा',
      'resolveNow': 'समस्या हल करें',
      'tamperProofProof': 'छेड़छाड़-मुक्त समाधान प्रमाण',
      'geofenceValid': 'जियोफेंस सीमा के भीतर',
      'captureProof': 'समय-अंकित फोटो लें',
      'uploadProof': 'प्रमाण अपलोड करें और AI जांच शुरू करें',
      'completedAudit': 'सत्यापित समाधान (ऑडिट प्रगति पर)',
      'officerCopilot': 'अधिकारी सह-पायलट',
      'bedrockClaude': 'बेडरॉक क्लाउड 3',
      'autoDispatch': 'ऑटो-डिस्पैच',
      'approvePwd': 'पीडब्ल्यूडी कार्य विभाग को स्वीकृत करें',
      'hotspotLedger': 'वार्ड 42 हॉटस्पॉट लेज़र',
      'askCopilot': 'वार्ड 42 के बारे में बेडरॉक AI से पूछें...',
      'reviewQueue': 'मैनुअल समीक्षा कतार (कम विश्वास स्कोर)',
      'coldZones': 'शांत क्षेत्र (14 दिनों से कोई शिकायत नहीं)',
      'wardComparison': 'वार्ड SLA व एस्केलेशन तुलना',
      'securityFooter': 'एडब्ल्यूएस कॉग्निटो • मुंबई क्षेत्र (ap-south-1) • AES-256 एन्क्रिप्शन',
      'loginTitle': 'सिविकपल्स नगर निगम पोर्टल',
      'loginSubtitle': 'एआई नागरिक ट्राइएज, जियोफेंस्ड सत्यापन और टेलीमेट्री ट्रैकिंग',
      'maskedPhoneNote': 'डेटा गोपनीयता कानून के तहत नागरिक फोन नंबर सुरक्षित रूप से छुपाए गए हैं',
    },
  };

  static String get(String key, String langCode) {
    final lang = _values[langCode] ?? _values['en']!;
    return lang[key] ?? _values['en']?[key] ?? key;
  }
}
